---
- hosts: mywebserver
  become: yes
  tasks: 
      - name:  install apache2 on ubuntu
        apt:
          name: apache2
          state: present
          when: ansible_os_family == "Debian"
      
      - name:  install nginx on ubuntu
        apt:
          name: nginx
          state: present
          when: ansible_os_family == "Debian"