---
- hosts: all
  become: yes
  tasks: 
      - name: install apache2 on ubuntu
        apt:
          name: apache2
          state: present
      
      - name: install nginx on ubuntu
        apt:
          name: nginx
          state: present

      - name: install apache2 on RedHat
        yum:
          name: apache2
          state: present
      
      - name: install nginx on RedHat
        yum:
          name: nginx
          state: present