---
- hosts: all
  become: yes
  tasks: 
      - name: install apache2 on ubuntu
        apt:
          name: apache2
          state: present
      
      - name: install nginx on ubuntu
        apt:
          name: nginx
          state: present

      - name: replace apache2 template with my jinja template
        template:
           src: myindex2.j2
           dest: /var/www/html/index.html
        notify: restartwebserver
    